"""modify all timestamp table to datetime

Revision ID: 26e709c7b179
Revises: e1b32fcf4cc5
Create Date: 2021-07-13 09:47:18.569592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e709c7b179'
down_revision = 'e1b32fcf4cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'post_time', type_=sa.DateTime)
    op.alter_column('topic', 'stop_track_at', type_=sa.DateTime)
    op.alter_column('topic', 'created_at', type_=sa.DateTime)
    op.alter_column('track', 'created_at', type_=sa.DateTime)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'post_time', type_=sa.TIMESTAMP)
    op.alter_column('topic', 'stop_track_at', type_=sa.TIMESTAMP)
    op.alter_column('topic', 'created_at', type_=sa.TIMESTAMP)
    op.alter_column('track', 'created_at', type_=sa.TIMESTAMP)
    # ### end Alembic commands ###
