"""add loop_count to  track_error

Revision ID: 48eb3d5714bf
Revises: 6b07f67dce50
Create Date: 2021-07-15 16:17:23.971632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48eb3d5714bf'
down_revision = '6b07f67dce50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_error', sa.Column('loop_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_error', 'loop_count')
    # ### end Alembic commands ###
