"""add triggered_at to track and monitor

Revision ID: 9f36fb5b4059
Revises: 26e709c7b179
Create Date: 2021-07-13 09:54:40.153210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f36fb5b4059'
down_revision = '26e709c7b179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor', sa.Column('triggered_at', sa.DateTime(), nullable=True))
    op.drop_column('monitor', 'created_at')
    op.add_column('track', sa.Column('triggered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'triggered_at')
    op.add_column('monitor', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_column('monitor', 'triggered_at')
    # ### end Alembic commands ###
