"""modify all datetime fields to timestamp

Revision ID: af8d811fcd0b
Revises: 6b58b7cd1329
Create Date: 2021-07-12 21:42:06.257934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8d811fcd0b'
down_revision = '6b58b7cd1329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'track_time')
    op.alter_column('topic', 'post_time', type_=sa.TIMESTAMP)
    op.alter_column('topic', 'stop_track_at', type_=sa.TIMESTAMP)
    op.alter_column('topic', 'created_at', type_=sa.TIMESTAMP)
    op.add_column('track', sa.Column('created_at', sa.TIMESTAMP))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'created_at')
    op.alter_column('topic', 'post_time', type_=sa.DateTime)
    op.alter_column('topic', 'stop_track_at', type_=sa.DateTime)
    op.alter_column('topic', 'created_at', type_=sa.DateTime)
    op.add_column('track', sa.Column('track_time', sa.DateTime))
    # ### end Alembic commands ###
