"""add triggered_at to topic

Revision ID: c18b61790b70
Revises: 9f36fb5b4059
Create Date: 2021-07-13 10:20:53.954572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18b61790b70'
down_revision = '9f36fb5b4059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('triggered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'triggered_at')
    # ### end Alembic commands ###
