"""add offset to track_error

Revision ID: d9c5a9e2eca4
Revises: 48eb3d5714bf
Create Date: 2021-07-15 16:59:04.317750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c5a9e2eca4'
down_revision = '48eb3d5714bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_error', sa.Column('offset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_error', 'offset')
    # ### end Alembic commands ###
