"""create monitor table

Revision ID: e1b32fcf4cc5
Revises: af8d811fcd0b
Create Date: 2021-07-13 09:46:24.377417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b32fcf4cc5'
down_revision = 'af8d811fcd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('new_topics_count', sa.Integer(), nullable=True),
    sa.Column('target_topics_count', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('execution_count', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor')
    # ### end Alembic commands ###
