"""add topic_id to topic

Revision ID: e2180472f6d1
Revises: 0d6f972ccc6a
Create Date: 2021-07-12 20:53:48.763055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2180472f6d1'
down_revision = '0d6f972ccc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('topic_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'topic_id')
    # ### end Alembic commands ###
