"""modify message from blob to string in track_error

Revision ID: f901affc9162
Revises: f331bc3e361c
Create Date: 2021-07-15 18:45:57.388220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f901affc9162'
down_revision = 'f331bc3e361c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track_error', 'message', type_=sa.String(10000))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track_error', 'message', type_=sa.BLOB)
    # ### end Alembic commands ###
